plugins { id 'com.android.application' }

android {
    namespace 'io.github.storageisolation.visibilityfix'
    compileSdk 35
    buildFeatures { buildConfig true }
    buildTypes {
        debug {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    defaultConfig {
        applicationId 'io.github.storageisolation.visibilityfix'
        minSdk 30
        targetSdk 28
        versionCode 20
        versionName '0.20'
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0'
    implementation 'com.google.android.material:material:1.12.0'
}
